"""измениния для удалния 

Revision ID: 99495b1c3b62
Revises: 0cbd23249f25
Create Date: 2024-10-17 22:36:40.210331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99495b1c3b62'
down_revision: Union[str, None] = '0cbd23249f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'major_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('students_major_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'majors', ['major_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_major_id_fkey', 'students', 'majors', ['major_id'], ['id'])
    op.alter_column('students', 'major_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
